require("core.noti")
require("core.layout")
-- require("core.theme")
require("theme.init")
require("core.bar.bar")
require("core.binding")
require("core.rule")
require("core.signal")
require("core.autostart")
