#!/bin/bash
# Loop through all attached batteries and format the info
# currntpwr=$(powerprofilesctl get)
# if [ "${currntpwr}" = "performance" ]; then
# 	pwr="-  Performance"
# elif [ "${currntpwr}" = "balanced" ]; then
# 	pwr="-  Balanced"
# elif [ "${currntpwr}" = "power-saver" ]; then
# 	pwr="-  Power Saver"
# fi

#          

for battery in /sys/class/power_supply/BAT?*; do
	# If non-first battery, print a space separator.
	[ -n "${capacity+x}" ] && printf " "
	# Sets up the status and capacity
	case "$(cat "$battery/status" 2>&1)" in
		"Full") status="full" ;;
		"Discharging") status="discharging" ;;
		"Charging") status="charging" ;;
		"Not charging") status="not-charging" ;;
		"Unknown") status="unknown" ;;
		*) exit 1 ;;
	esac
	icon=""
	capacity="$(cat "$battery/capacity" 2>&1)"
	if   [ "${status}" = "charging" ]; then 
		icon=" "
	elif [ "$capacity" -ge 100 ]; then 
		icon=" "
	elif [ "$capacity" -gt 90 ]; then 
		icon=""
	elif [ "$capacity" -gt 80 ]; then 
		icon=""
	elif [ "$capacity" -gt 70 ]; then 
		icon=""
	elif [ "$capacity" -gt 60 ]; then 
		icon=""
	elif [ "$capacity" -gt 50 ]; then 
		icon=""
	elif [ "$capacity" -gt 40 ]; then 
		icon=""
	elif [ "$capacity" -gt 30 ]; then 
		icon=""
	elif [ "$capacity" -gt 20 ]; then 
		icon=""
	elif [ "$capacity" -gt 10 ]; then 
		icon=""
	else									 
		icon=""
	fi
# 
# 
# 
	# Prints the info
	printf " %s%s%% " "$icon" "$capacity";
done && printf "\\n"