#!/bin/bash

vol=$(pamixer --get-volume)
[ $(pamixer --get-mute) = true ] && echo "  $vol% " && exit
if [ "$vol" -gt "50" ]; then
    icon="  " 
elif [ "$vol" -gt "0" ]; then
    icon="  "
else
    icon="  "
fi

echo "$icon$((vol * 2 / 3))% "
